services:
  - type: web
    name: tknd-admin-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: >
      gunicorn -k uvicorn.workers.UvicornWorker -w 1 main:app
      --bind 0.0.0.0:$PORT --timeout 120
